// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.0
// source: pb/hello.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_BindHello_FullMethodName = "/pb.Greeter/BindHello"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// grpc 基础工作方式
	// rpc SayHello(HelloRequest) returns (HelloResponse) {}
	// 服务端流式 RPC
	// rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
	// 客户端流式 RPC
	// rpc LotsOfGreetings(stream HelloRequest) returns (HelloResponse);
	// 双向流式数据
	BindHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_BindHelloClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) BindHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_BindHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], Greeter_BindHello_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBindHelloClient{stream}
	return x, nil
}

type Greeter_BindHelloClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greeterBindHelloClient struct {
	grpc.ClientStream
}

func (x *greeterBindHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBindHelloClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// grpc 基础工作方式
	// rpc SayHello(HelloRequest) returns (HelloResponse) {}
	// 服务端流式 RPC
	// rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
	// 客户端流式 RPC
	// rpc LotsOfGreetings(stream HelloRequest) returns (HelloResponse);
	// 双向流式数据
	BindHello(Greeter_BindHelloServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) BindHello(Greeter_BindHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method BindHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_BindHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).BindHello(&greeterBindHelloServer{stream})
}

type Greeter_BindHelloServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterBindHelloServer struct {
	grpc.ServerStream
}

func (x *greeterBindHelloServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBindHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BindHello",
			Handler:       _Greeter_BindHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/hello.proto",
}
